### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by klp2** [jmaslak/IP-Random#1]
Hi there.

It looks like you are both setting a version in the package declaration (which I believe sets NAMESPACE::$VERSION automagically) and having dist.ini insert a different $VERSION. This seems confusing to me, and is also confusing to our tooling at $work. Would it make sense to just do one or the other?

**Comment by jmaslak** [comment]
I'll take a look this evening - I didn't intend to have dueling versions, so this is almost certainly a bug.

**Comment by jmaslak** [comment]
I removed the version I set in the package declaration and released this along with some code debt cleanup (nothing that should impact performance or functionality) as version 1.002.  Please let me know if that version doesn't solve the issue with the $VERSION.

Thanks for reporting the issue - this was definitely a bug.

**Comment by klp2** [comment]
That worked, thanks!
